export const signupFields = [
  {
    name: 'firstName',
    label: 'First Name',
    placeholder: 'First Name',
    secureTextEntry: false,
    autoCapitalize: 'words',
    keyboardType: 'default',
  },
  {
    name: 'lastName',
    label: 'Last Name',
    placeholder: 'Last Name',
    secureTextEntry: false,
    autoCapitalize: 'words',
    keyboardType: 'default',
  },
  {
    name: 'username',
    label: 'Username',
    placeholder: 'Username',
    secureTextEntry: false,
    autoCapitalize: 'none',
    keyboardType: 'default',
  },
  {
    name: 'email',
    label: 'Email Address',
    placeholder: 'Email Address',
    secureTextEntry: false,
    autoCapitalize: 'none',
    keyboardType: 'email-address',
  },
  {
    name: 'password',
    label: 'Password',
    placeholder: 'Password',
    secureTextEntry: true,
    keyboardType: 'default',
  },
  {
    name: 'confirmPassword',
    label: 'Confirm Password',
    placeholder: 'Confirm Password',
    secureTextEntry: true,
    keyboardType: 'default',
  },
  {
    name: 'phoneNumber',
    label: 'Phone Number',
    placeholder: 'Phone Number',
    secureTextEntry: false,
    autoCapitalize: 'none',
    keyboardType: 'phone-pad',
  },
  {
    name: 'age',
    label: 'Age',
    placeholder: 'Age',
    secureTextEntry: false,
    autoCapitalize: 'none',
    keyboardType: 'numeric',
  },
  {
    name: 'gender',
    label: 'Gender',
    placeholder: 'Select Gender',
    secureTextEntry: false,
    autoCapitalize: 'none',
    keyboardType: 'default',
    options: [
      { label: 'Male', value: 'male' },
      { label: 'Female', value: 'female' },
      { label: 'Other', value: 'other' },
    ],
  },
];
